[package]
name = "pidfd-util"
version = "0.1.0"
edition = "2024"

[features]
default = []
nightly = []

[dependencies]
libc = { version = "0.2.171" }
async-io = { version = "2.4.0" }

[dev-dependencies]
futures-lite = "2.0"
